services:
  postgres:
    image: postgres:16
    container_name: docai_pg
    restart: unless-stopped
    ports: ["5432:5432"]
    environment:
      POSTGRES_USER: ${PGUSER:?set PGUSER in .env}
      POSTGRES_PASSWORD: ${PGPASSWORD:?set PGPASSWORD in .env}
      POSTGRES_DB: ${PGDATABASE:?set PGDATABASE in .env}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
