name: doc_analytics_ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - boto3
  - uvicorn
  - fastapi
  - pydantic>=2
  - sqlalchemy>=2
  - psycopg2
  - numpy
  - pandas
  - scikit-learn
  - pytest
  - pytest-cov
  - httpx
  - black
  - ruff
  - pre-commit
  - python-dotenv
  - pip:
      - alembic==1.13.2
      - streamlit
