name: doc_analytics_ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - fastapi
  - uvicorn
  - pydantic>=2
  - sqlalchemy>=2
  - psycopg2
  - numpy
  - pandas
  - scikit-learn
  - streamlit
  - requests
  - pytest
  - pytest-cov
  - httpx
  - black
  - pre-commit
  - ruff
  - python-dotenv
  - pip:
      - alembic==1.13.2
