"""baseline schema

Revision ID: db653e4c685e
Revises:
Create Date: 2025-08-15 16:17:50.196578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "db653e4c685e"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_transcripts_id", table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_table("object_store_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_store_items",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("bucket", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("size_bytes", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("etag", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="object_store_items_pkey"),
        sa.UniqueConstraint(
            "bucket",
            "key",
            name="uq_bucket_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "transcripts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "source", sa.VARCHAR(length=256), autoincrement=False, nullable=False
        ),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("label", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="transcripts_pkey"),
    )
    op.create_index("ix_transcripts_id", "transcripts", ["id"], unique=False)
    # ### end Alembic commands ###
